### ISSUE TITLE
Cannot run partest : ForkError : scala/tools/nsc/Properties$

### ISSUE THREAD

**Issue by backuitist** [scala/scala-partest-interface#6]
I'm trying to test a macro with partest. I followed the instructions to set up my projects:
https://github.com/backuity/ansi-interpolator/blob/master/project/Build.scala
When I run `test` I get the following stack trace:

```
sbt.ForkMain$ForkError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at scala.tools.partest.PartestTask.SBTRunner(TestingInterface.scala:91)
	at scala.tools.partest.PartestTask.execute(TestingInterface.scala:70)
	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: sbt.ForkMain$ForkError: scala/tools/nsc/Properties$
	at scala.tools.partest.nest.AntRunner.<init>(AntRunner.scala:20)
	at scala.tools.partest.nest.SBTRunner.<init>(SBTRunner.scala:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at scala.tools.partest.PartestTask.SBTRunner(TestingInterface.scala:91)
	at scala.tools.partest.PartestTask.execute(TestingInterface.scala:70)
	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: sbt.ForkMain$ForkError: scala.tools.nsc.Properties$
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at scala.tools.partest.nest.AntRunner.<init>(AntRunner.scala:20)
	at scala.tools.partest.nest.SBTRunner.<init>(SBTRunner.scala:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at scala.tools.partest.PartestTask.SBTRunner(TestingInterface.scala:91)
	at scala.tools.partest.PartestTask.execute(TestingInterface.scala:70)
	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by SethTisue** [comment]
closing because #16 folds scala-partest-interface into partest itself. sorry, I'm not sure why there was never any activity on this issue. we're very actively working on the sbt build for Scala these days, so if any of this is still applicable, please consider submitting a new issue over in the scala-partest repo.
